// Ethical-hacking / bug-bounty knowledge base. Breadth over every major domain,
// per-language pitfalls, payload cheats, a methodology, and a tool catalog that
// maps external tools to Shakuni's in-house equivalents. Entries are LEADS and
// references for AUTHORIZED testing only, always confirm scope and impact.

export type Category =
  | "web" | "api" | "web3" | "mobile" | "network" | "cloud"
  | "binary" | "auth" | "recon" | "language" | "method" | "tool";

export type Sev = "critical" | "high" | "medium" | "low" | "info";

export interface Entry {
  id: string;
  title: string;
  category: Category;
  tags: string[];
  sev?: Sev;
  what: string;
  find: string;
  example?: string;
  note?: string;
}

export interface Cat { id: Category; label: string; color: string; blurb: string }

export const CATEGORIES: Cat[] = [
  { id: "web", label: "Web app", color: "#7d97e6", blurb: "OWASP-class web vulnerabilities." },
  { id: "api", label: "API", color: "#3ac1d9", blurb: "REST / GraphQL / auth API flaws." },
  { id: "web3", label: "Web3 / contracts", color: "#ab8df1", blurb: "Smart-contract and bridge bugs." },
  { id: "mobile", label: "Mobile", color: "#53c18b", blurb: "Android / iOS app security." },
  { id: "network", label: "Network / infra", color: "#e0a94a", blurb: "Hosts, DNS, TLS, services." },
  { id: "cloud", label: "Cloud", color: "#e585a7", blurb: "AWS / GCP / K8s misconfig." },
  { id: "binary", label: "Binary / RE", color: "#d98b5f", blurb: "Memory corruption & reversing." },
  { id: "auth", label: "Auth / crypto", color: "#8fb0ff", blurb: "Sessions, JWT, OAuth, crypto." },
  { id: "recon", label: "Recon / OSINT", color: "#9aa6b2", blurb: "Mapping the attack surface." },
  { id: "language", label: "Languages", color: "#d7c04a", blurb: "Per-language security pitfalls." },
  { id: "method", label: "Methodology", color: "#aeb6c2", blurb: "The bug-bounty process." },
  { id: "tool", label: "Tools", color: "#6fd0c0", blurb: "External tools ↔ Shakuni equivalents." },
];

export const CATEGORY: Record<Category, Cat> = Object.fromEntries(CATEGORIES.map((c) => [c.id, c])) as Record<Category, Cat>;

export const ENTRIES: Entry[] = [
  // ---------------- WEB ----------------
  { id: "xss", title: "Cross-Site Scripting (XSS)", category: "web", sev: "high", tags: ["xss", "injection", "javascript"],
    what: "Attacker-controlled input is reflected/stored and executed as script in another user's browser (reflected, stored, DOM-based).",
    find: "Inject a unique marker in every parameter, header, and path segment; look for it unescaped in HTML, attributes, JS, or sinks like innerHTML/eval. DOM XSS: trace sources (location, document.referrer) to sinks.",
    example: "\"><script>alert(document.domain)</script>\n'-alert(1)-'\n<img src=x onerror=alert(1)>\njavascript:alert(1)",
    note: "Impact needs a sensitive context (session theft, account actions). Self-XSS alone is usually out of scope." },
  { id: "sqli", title: "SQL Injection", category: "web", sev: "critical", tags: ["sqli", "injection", "database"],
    what: "Untrusted input alters a SQL query, leaking or modifying data or achieving RCE.",
    find: "Add ' \" and SQL metacharacters; watch for errors, boolean differences, or time delays. Test ORDER BY, UNION, and blind (boolean/time) techniques.",
    example: "' OR '1'='1\n1' UNION SELECT NULL,version()-- -\n1' AND SLEEP(5)-- -\n1);SELECT pg_sleep(5)--",
    note: "sqlmap automates it; confirm impact (which data). NoSQL variants: {\"$gt\":\"\"}, [$ne]=1." },
  { id: "ssrf", title: "Server-Side Request Forgery (SSRF)", category: "web", sev: "high", tags: ["ssrf", "cloud", "metadata"],
    what: "The server makes an attacker-controlled request, reaching internal services or cloud metadata.",
    find: "Any feature that fetches a URL (webhooks, image/PDF import, link preview, imports). Point it at internal IPs and the cloud metadata endpoint; use a collaborator to confirm blind SSRF.",
    example: "http://169.254.169.254/latest/meta-data/iam/security-credentials/\nhttp://metadata.google.internal/computeMetadata/v1/\nhttp://127.0.0.1:port/ · http://[::1]/ · http://2130706433/",
    note: "Bypass filters with redirects, DNS rebinding, octal/hex/decimal IPs, and alternate schemes (gopher://, file://)." },
  { id: "idor", title: "IDOR / Broken Object-Level Auth (BOLA)", category: "web", sev: "high", tags: ["idor", "bola", "authz", "access-control"],
    what: "An object reference (id) isn't checked against the caller's ownership, exposing other users' data/actions.",
    find: "With two of your own accounts, swap IDs (numeric, UUID, hash) in paths, params, and bodies. Watch for 2xx where you expected 403/404, and partial leaks in error bodies.",
    example: "GET /api/v1/users/{OTHER_ID}\nPATCH /orders/{OTHER_ID} {\"owner\":\"me\"}",
    note: "Shakuni: use the Request Workbench → IDOR matrix. The #1 web2 bug class." },
  { id: "csrf", title: "Cross-Site Request Forgery", category: "web", sev: "medium", tags: ["csrf", "state"],
    what: "A victim's authenticated browser is tricked into performing a state-changing action.",
    find: "Find sensitive actions without a CSRF token (or token not validated); check SameSite cookie settings and whether JSON/Content-Type is enforced.",
    note: "Low value on unauthenticated or no-sensitive-action forms (commonly out of scope)." },
  { id: "ssti", title: "Server-Side Template Injection", category: "web", sev: "critical", tags: ["ssti", "injection", "rce"],
    what: "Input is evaluated by a template engine, often leading to RCE.",
    find: "Inject polyglots in any field that is reflected after processing; a math result confirms it, then escalate per engine.",
    example: "${7*7}  {{7*7}}  <%= 7*7 %>  #{7*7}\n{{config.__class__.__init__.__globals__}}  (Jinja2)",
    note: "Identify the engine (Jinja2, Twig, Freemarker, ERB) before escalating." },
  { id: "xxe", title: "XML External Entity (XXE)", category: "web", sev: "high", tags: ["xxe", "xml", "ssrf"],
    what: "An XML parser resolves external entities, enabling file read, SSRF, or DoS.",
    find: "Any XML input (SOAP, SAML, SVG, DOCX, config upload). Inject a DOCTYPE with an external entity; use OOB for blind.",
    example: "<!DOCTYPE x [<!ENTITY e SYSTEM \"file:///etc/passwd\">]><x>&e;</x>" },
  { id: "deser", title: "Insecure Deserialization", category: "web", sev: "critical", tags: ["deserialization", "rce"],
    what: "Untrusted serialized data is deserialized into objects, enabling RCE or logic abuse.",
    find: "Look for serialized blobs in cookies/params (Java rO0, PHP O:, .NET, Python pickle, Ruby). Use ysoserial / gadget chains.",
    note: "Java magic bytes base64 'rO0AB'; PHP 'O:8:'." },
  { id: "openredirect", title: "Open Redirect", category: "web", sev: "low", tags: ["redirect", "oauth"],
    what: "A redirect target is attacker-controlled, enabling phishing or token theft when chained.",
    find: "Params like ?next=, ?url=, ?redirect=, ?returnTo=. Try absolute URLs, //evil.com, https:evil.com, userinfo tricks.",
    example: "?next=//evil.com  ?url=https://good.com@evil.com  ?redirect=/\\evil.com",
    note: "Low alone; high when it leaks an OAuth code/token or SSO assertion." },
  { id: "pathtrav", title: "Path Traversal / LFI", category: "web", sev: "high", tags: ["lfi", "traversal", "files"],
    what: "Input reaches a filesystem path, reading files outside the intended directory.",
    find: "File/download/template/lang params. Try ../ sequences, encodings, null bytes, and absolute paths.",
    example: "../../../../etc/passwd\n..%2f..%2f..%2fetc%2fpasswd\n....//....//etc/passwd" },
  { id: "cmdi", title: "OS Command Injection", category: "web", sev: "critical", tags: ["rce", "injection", "command"],
    what: "Input is passed to a shell, running arbitrary commands.",
    find: "Features invoking system tools (ping, convert, ffmpeg, git). Inject separators and confirm with time/OOB.",
    example: "; id\n| id\n`id`\n$(id)\n&& sleep 5\n%0a id",
    note: "On the Solidity/Rust side, the analog is the interpolated-execSync pattern, see the Contract Scanner." },
  { id: "cors", title: "CORS Misconfiguration", category: "web", sev: "medium", tags: ["cors", "origin"],
    what: "Overly permissive CORS lets a malicious origin read authenticated responses.",
    find: "Send Origin: https://evil.com; if ACAO reflects it AND ACA-Credentials: true, it's exploitable. Check null origin and subdomain trust.",
    note: "ACAO: * without credentials is usually not a vuln." },
  { id: "logic", title: "Business Logic Flaws", category: "web", sev: "high", tags: ["logic", "workflow", "race"],
    what: "The app allows a sequence or value the business didn't intend (negative quantities, skipped steps, replayed coupons, race conditions).",
    find: "Model the intended workflow, then break ordering/assumptions: skip steps, replay requests, send negative/huge values, race parallel requests.",
    note: "Highest-value, least-automatable class, read the feature like the developer." },
  { id: "smuggle", title: "HTTP Request Smuggling", category: "web", sev: "high", tags: ["smuggling", "desync", "proxy"],
    what: "Front-end and back-end disagree on request boundaries (CL.TE / TE.CL), poisoning other users' requests.",
    find: "Craft ambiguous Content-Length vs Transfer-Encoding; measure timing/response differences.",
    note: "Burp's HTTP Request Smuggler; high impact, tricky to confirm safely." },
  { id: "upload", title: "Unrestricted File Upload", category: "web", sev: "high", tags: ["upload", "rce"],
    what: "Upload validation can be bypassed to store an executable/handler file.",
    find: "Bypass extension/content-type checks (double ext, null byte, magic bytes, polyglot); find where it's served and whether it executes.",
    example: "shell.php.jpg · .phtml · content-type image/png + <?php code ?>" },

  // ---------------- API ----------------
  { id: "api-bola", title: "BOLA (API object auth)", category: "api", sev: "high", tags: ["bola", "idor", "authz"],
    what: "API endpoints keyed by object id without verifying ownership, the top API risk.",
    find: "Enumerate IDs across tenants with two of your own accounts; check every method (GET/PUT/DELETE).",
    note: "Shakuni Request Workbench → IDOR matrix." },
  { id: "api-massassign", title: "Mass Assignment / BOPLA", category: "api", sev: "high", tags: ["mass-assignment", "authz"],
    what: "Client can set object properties it shouldn't (role, isAdmin, balance, ownerId).",
    find: "Add extra fields to create/update bodies and see if they stick. Diff the read model for hidden fields to try.",
    example: "PATCH /users/me {\"role\":\"admin\",\"verified\":true}" },
  { id: "api-jwt", title: "Broken Auth (JWT)", category: "api", sev: "critical", tags: ["jwt", "auth"],
    what: "JWT verification flaws: alg=none, alg confusion (RS256→HS256), weak HMAC secret, kid injection, no expiry check.",
    find: "Decode the token; try alg none, swap RS256 to HS256 signing with the public key, brute weak secrets, tamper claims.",
    example: "header {\"alg\":\"none\"} · {\"alg\":\"HS256\"} signed with the RSA public key",
    note: "Shakuni Chain Lab can craft/verify ECDSA; jwt_tool for the rest." },
  { id: "api-exposure", title: "Excessive Data Exposure", category: "api", sev: "medium", tags: ["data", "exposure"],
    what: "API returns more fields than the UI shows (PII, internal flags, other users' data).",
    find: "Read raw API responses, not the UI; look for fields the client filters client-side." },
  { id: "api-ratelimit", title: "Missing Rate Limiting", category: "api", sev: "medium", tags: ["rate-limit", "bruteforce"],
    what: "No throttling on sensitive actions (login, OTP, password reset, coupon).",
    find: "Send many requests; watch for lockout/throttle. Most impactful on auth/OTP endpoints.",
    note: "Often out of scope on non-auth endpoints, check program rules." },
  { id: "api-graphql", title: "GraphQL Issues", category: "api", sev: "high", tags: ["graphql", "introspection"],
    what: "Introspection exposure, nested-query DoS, batching to bypass rate limits, field-level authz gaps, injection.",
    find: "Query __schema introspection; abuse aliases/batching; deeply nest queries; test authz per field.",
    example: "{__schema{types{name fields{name}}}}" },
  { id: "api-versions", title: "Improper Inventory (old APIs)", category: "api", sev: "medium", tags: ["versioning", "shadow-api"],
    what: "Deprecated/undocumented API versions with weaker controls stay live.",
    find: "Try /v1 vs /v2, .json, internal hostnames, old mobile endpoints from JS/APK; compare auth strength." },

  // ---------------- WEB3 ----------------
  { id: "w3-reentrancy", title: "Reentrancy", category: "web3", sev: "critical", tags: ["reentrancy", "solidity"],
    what: "An external call re-enters the contract before state is updated, draining funds.",
    find: "Find external calls (transfer, call, callbacks, ERC-777/1155 hooks) before state writes; check for nonReentrant / CEI.",
    note: "Shakuni Solidity Analyzer flags low-level calls; prove it in the Foundry Harness." },
  { id: "w3-access", title: "Missing Access Control", category: "web3", sev: "critical", tags: ["access-control", "authz"],
    what: "A privileged function (mint, upgrade, withdraw, setter) lacks onlyOwner/role checks.",
    find: "List state-mutating external/public functions; verify each has a modifier or msg.sender check.",
    note: "AST detector 'priv-no-guard' in the Solidity Analyzer." },
  { id: "w3-sig", title: "Signature Replay / Malleability", category: "web3", sev: "high", tags: ["signature", "ecdsa", "replay"],
    what: "A signed message can be replayed (no nonce/chainId/domain binding) or an ecrecover lacks malleability/zero-address guards.",
    find: "Check that signed digests bind a nonce, chainId, and contract; that ecrecover rejects s>N/2 and address(0).",
    note: "Craft/verify in Chain Lab; see the CCTP checklist in the Contract Scanner." },
  { id: "w3-bridge", title: "Bridge / Attestation Flaws", category: "web3", sev: "critical", tags: ["bridge", "cctp", "attestation"],
    what: "Mint-on-destination authorized by attestations: threshold not enforced, duplicate/unordered signers, nonce replay, wrong domain binding.",
    find: "Verify threshold == exact count of distinct enabled, strictly-increasing signers; used-nonce persisted; destination domain/caller bound.",
    note: "The whole CCTP methodology checklist lives in the Contract Scanner." },
  { id: "w3-oracle", title: "Oracle / Price Manipulation", category: "web3", sev: "critical", tags: ["oracle", "flashloan", "defi"],
    what: "A protocol reads a manipulable price (spot DEX reserves) and can be drained via a flash loan.",
    find: "Find price sources; if spot/instantaneous and not TWAP/Chainlink, model a flash-loan manipulation.",
    note: "Reproduce with a forked Foundry invariant test." },
  { id: "w3-int", title: "Integer Overflow / Rounding", category: "web3", sev: "high", tags: ["integer", "math"],
    what: "Unchecked math wraps, or division rounding leaks value over many calls.",
    find: "Check unchecked{} blocks, casts (uint256→uint64), and division-before-multiplication. Fuzz with Foundry.",
    note: "Solidity 0.8 checks by default; the risk is in unchecked and casts." },
  { id: "w3-init", title: "Unprotected Initializer / Upgrade", category: "web3", sev: "critical", tags: ["upgradeability", "proxy", "initializer"],
    what: "Proxy initializer re-callable/front-runnable, or UUPS _authorizeUpgrade not access-controlled.",
    find: "Confirm initializer/reinitializer modifier + atomic deploy; _authorizeUpgrade is onlyOwner; storage is namespaced (EIP-7201).",
    note: "AST detectors 'initializer' and 'authorize-upgrade' in the Solidity Analyzer." },
  { id: "w3-txorigin", title: "tx.origin Authorization", category: "web3", sev: "high", tags: ["tx-origin", "phishing"],
    what: "Using tx.origin for auth lets a malicious intermediary contract act for a victim.",
    find: "Grep/AST for tx.origin in require/if; should be msg.sender.", note: "AST detector 'tx-origin'." },
  { id: "w3-delegatecall", title: "delegatecall / Storage Collision", category: "web3", sev: "high", tags: ["delegatecall", "proxy"],
    what: "delegatecall runs external code in this storage context; untrusted target or mismatched layout corrupts storage.",
    find: "Verify the target is immutable/trusted and storage layouts match.", note: "AST detector 'delegatecall'." },

  // ---------------- MOBILE ----------------
  { id: "m-storage", title: "Insecure Data Storage", category: "mobile", sev: "medium", tags: ["android", "ios", "storage"],
    what: "Sensitive data (tokens, PII) stored unencrypted in SharedPreferences, plists, SQLite, or logs.",
    find: "Decompile the app; inspect app data dir, Keychain/Keystore usage, and logcat for secrets." },
  { id: "m-secrets", title: "Hardcoded Secrets", category: "mobile", sev: "high", tags: ["secrets", "apk"],
    what: "API keys, signing keys, or endpoints baked into the binary.",
    find: "Unzip the APK/IPA; strings/grep the decompiled code and resources; check BuildConfig and native libs.",
    note: "Confirm the key is live and privileged, not a public/test key." },
  { id: "m-pinning", title: "Cert Pinning Bypass", category: "mobile", sev: "info", tags: ["tls", "frida", "mitm"],
    what: "Bypassing pinning to intercept and test the app's API traffic.",
    find: "Use Frida/objection to hook the pinning check, then proxy through Burp/mitmproxy.",
    note: "A testing technique, not a bug itself; the bugs are in the exposed API." },
  { id: "m-exported", title: "Exported Components (Android)", category: "mobile", sev: "high", tags: ["android", "ipc", "intent"],
    what: "Exported Activities/Services/Receivers/Providers callable by other apps without permission.",
    find: "Parse AndroidManifest for exported=true; invoke them with crafted Intents; check ContentProvider authority access.",
    example: "adb shell am start -n pkg/.Activity --es extra value" },
  { id: "m-deeplink", title: "Deep Link / URL Scheme Hijack", category: "mobile", sev: "medium", tags: ["deeplink", "oauth"],
    what: "Custom scheme / universal link handling that leaks tokens or triggers actions.",
    find: "Enumerate schemes/intent-filters; test unvalidated params and OAuth redirect interception." },
  { id: "m-webview", title: "Insecure WebView", category: "mobile", sev: "high", tags: ["webview", "xss", "rce"],
    what: "WebView with JS enabled + addJavascriptInterface, file access, or loading untrusted content.",
    find: "Find loadUrl of attacker-influenced URLs, exposed JS bridges, and setAllowFileAccess." },

  // ---------------- NETWORK / INFRA ----------------
  { id: "n-ports", title: "Service / Port Enumeration", category: "network", sev: "info", tags: ["nmap", "recon"],
    what: "Map open ports and service versions to find exposed/outdated services.",
    find: "Scan the in-scope ranges; version-detect; check for known-vuln versions.",
    example: "nmap -sV -sC -p- target  ·  nmap --script vuln target" },
  { id: "n-takeover", title: "Subdomain Takeover", category: "network", sev: "high", tags: ["dns", "takeover"],
    what: "A DNS record points to a deprovisioned service you can claim (S3, GitHub Pages, Heroku, Azure).",
    find: "Enumerate subdomains; find CNAMEs to third-parties returning 'NoSuchBucket'/404 fingerprints; claim it.",
    note: "Tools: subjack, nuclei takeover templates; confirm you can serve content." },
  { id: "n-dns", title: "DNS Misconfiguration", category: "network", sev: "medium", tags: ["dns", "zone-transfer"],
    what: "Zone transfer exposure, dangling records, missing CAA, or internal names leaked.",
    find: "Try AXFR; enumerate records; look for internal hostnames in SPF/TXT." },
  { id: "n-tls", title: "TLS / SSL Issues", category: "network", sev: "low", tags: ["tls", "crypto"],
    what: "Weak protocols/ciphers, expired/mismatched certs, Heartbleed-era bugs.",
    find: "Scan the endpoint's TLS config.", example: "testssl.sh target  ·  sslscan target",
    note: "Mostly informational unless it enables a concrete attack." },
  { id: "n-defaultcreds", title: "Default / Weak Credentials", category: "network", sev: "high", tags: ["creds", "auth"],
    what: "Admin panels, databases, or devices with default or guessable credentials.",
    find: "Identify the product; try documented default creds and common pairs on exposed admin interfaces." },

  // ---------------- CLOUD ----------------
  { id: "c-bucket", title: "Object Storage Exposure", category: "cloud", sev: "high", tags: ["s3", "gcs", "bucket"],
    what: "Public/listable S3/GCS/Azure buckets exposing data, or writable buckets.",
    find: "Enumerate bucket names from the app/JS; test list/read/write ACLs.",
    example: "aws s3 ls s3://bucket --no-sign-request" },
  { id: "c-imds", title: "SSRF → Cloud Metadata (IMDS)", category: "cloud", sev: "critical", tags: ["ssrf", "imds", "iam"],
    what: "SSRF reaching the instance metadata service yields IAM credentials → cloud account access.",
    find: "From an SSRF, fetch the metadata endpoint; use returned creds to enumerate the account.",
    example: "http://169.254.169.254/latest/meta-data/iam/security-credentials/ROLE",
    note: "IMDSv2 requires a token header, chainable if the SSRF allows headers." },
  { id: "c-iam", title: "IAM Misconfiguration / PrivEsc", category: "cloud", sev: "critical", tags: ["iam", "privesc"],
    what: "Over-permissive IAM policies allow privilege escalation (iam:PassRole, *:*, policy edits).",
    find: "Enumerate permissions with low-priv creds; find escalation paths.",
    note: "Tools: pacu, ScoutSuite, cloudsplaining." },
  { id: "c-k8s", title: "Exposed K8s / Dashboards", category: "cloud", sev: "high", tags: ["kubernetes", "exposure"],
    what: "Unauthenticated Kubelet/API, dashboards, or etcd exposed to the internet.",
    find: "Probe 10250/6443/2379 and common dashboards; check anonymous access." },

  // ---------------- BINARY / RE ----------------
  { id: "b-bof", title: "Stack Buffer Overflow", category: "binary", sev: "critical", tags: ["pwn", "memory"],
    what: "Writing past a stack buffer overwrites the return address → control flow hijack.",
    find: "Find unbounded copies (gets, strcpy, memcpy with bad len); fuzz inputs; check mitigations (canary, NX, PIE, ASLR).",
    note: "Modern targets need ROP/ret2libc and an info leak to beat ASLR." },
  { id: "b-fmt", title: "Format String", category: "binary", sev: "high", tags: ["pwn", "memory"],
    what: "User input used as a format string enables arbitrary read/write.",
    find: "printf(user) patterns; %x/%n to leak/write.", example: "%p %p %p  ·  %n" },
  { id: "b-uaf", title: "Use-After-Free / Double-Free", category: "binary", sev: "critical", tags: ["pwn", "heap"],
    what: "Using freed memory leads to control of heap objects and function pointers.",
    find: "Track object lifetimes; look for free without nulling and later use; heap grooming to exploit." },
  { id: "b-re", title: "Reversing Workflow", category: "binary", sev: "info", tags: ["reversing", "ghidra"],
    what: "Static/dynamic analysis of a binary to find logic and vulns.",
    find: "Disassemble/decompile; identify input handling and dangerous calls; debug to confirm.",
    note: "Tools: Ghidra (free), IDA, Binary Ninja, radare2, gdb+pwndbg." },

  // ---------------- AUTH / CRYPTO ----------------
  { id: "a-oauth", title: "OAuth / SSO Flaws", category: "auth", sev: "high", tags: ["oauth", "sso", "redirect"],
    what: "redirect_uri validation bypass, missing/replayed state (CSRF), code/token leakage, account linking takeover.",
    find: "Tamper redirect_uri (subdomains, paths, //, @); drop/reuse state; try linking an unverified-email identity to a victim.",
    note: "This exact class was the open lead on Privy and Circle web2." },
  { id: "a-saml", title: "SAML Signature Wrapping", category: "auth", sev: "critical", tags: ["saml", "xml", "auth"],
    what: "XML signature wrapping / comment injection to forge assertions and impersonate users.",
    find: "Intercept the SAMLResponse; move/duplicate signed elements; inject comments in NameID.",
    note: "Tools: SAML Raider (Burp extension)." },
  { id: "a-session", title: "Session Management", category: "auth", sev: "medium", tags: ["session", "cookies"],
    what: "Fixation, predictable tokens, no rotation on login, missing HttpOnly/Secure/SameSite, long-lived sessions.",
    find: "Check token entropy, rotation on privilege change, invalidation on logout/reset." },
  { id: "a-reset", title: "Password Reset Poisoning / Weakness", category: "auth", sev: "high", tags: ["reset", "takeover"],
    what: "Host-header poisoning of reset links, leaked tokens, weak token entropy, or no account binding → ATO.",
    find: "Tamper Host/X-Forwarded-Host on reset; inspect token in response/referrer; test token reuse and user binding." },
  { id: "a-crypto", title: "Weak Cryptography", category: "auth", sev: "medium", tags: ["crypto", "randomness"],
    what: "ECB mode, static IVs, predictable randomness (Math.random for tokens), padding oracles, custom crypto.",
    find: "Identify crypto use; look for reused IVs/nonces, weak PRNGs, and decryptable error oracles.",
    note: "Chain Lab helps reason about ECDSA/keccak/EIP-712 specifically." },

  // ---------------- RECON ----------------
  { id: "r-subdomains", title: "Subdomain Enumeration", category: "recon", sev: "info", tags: ["recon", "subdomains"],
    what: "Discover hosts in scope to widen the attack surface.",
    find: "Passive (CT logs, sources) + active brute; resolve and probe live hosts.",
    example: "subfinder -d target | httpx  ·  amass enum -d target" },
  { id: "r-content", title: "Content / Directory Discovery", category: "recon", sev: "info", tags: ["recon", "fuzzing"],
    what: "Find hidden endpoints, files, and parameters.",
    find: "Fuzz paths and params with good wordlists; diff responses by status/length.",
    example: "ffuf -u https://t/FUZZ -w list.txt  ·  ffuf -u https://t/?FUZZ=x" },
  { id: "r-github", title: "GitHub / Secret Leaks", category: "recon", sev: "high", tags: ["osint", "secrets", "git"],
    what: "Leaked credentials, keys, and internal info in public repos and git history.",
    find: "Search org repos and dorks; scan history (even deleted lines remain).",
    example: "trufflehog / gitleaks on the repo · GitHub code search for the org's domains/keys",
    note: "Verify a leaked key is live and in-scope before reporting; test keys (Anvil) are not secrets." },
  { id: "r-js", title: "JavaScript Analysis", category: "recon", sev: "info", tags: ["recon", "js", "endpoints"],
    what: "Front-end JS reveals API endpoints, params, hidden features, and sometimes secrets.",
    find: "Pull and beautify all JS; grep for URLs, API routes, feature flags, and keys; map the API from the client.",
    note: "For a target's SDK, use Shakuni's source tooling to read the client code." },
  { id: "r-wayback", title: "Historical / Archive Recon", category: "recon", sev: "info", tags: ["osint", "wayback"],
    what: "Old endpoints and params from archives that may still work with weaker controls.",
    find: "Pull URLs from web archives and historical sources; test the dead-looking ones.",
    example: "gau / waybackurls target" },

  // ---------------- LANGUAGES ----------------
  { id: "l-solidity", title: "Solidity pitfalls", category: "language", tags: ["solidity", "evm"], sev: "info",
    what: "reentrancy, tx.origin auth, delegatecall storage collisions, unchecked low-level calls, unprotected initializers/upgrades, unchecked math casts, signature replay/malleability, front-running (MEV).",
    find: "Use Shakuni's Contract Scanner (regex) + Solidity Analyzer (AST); verify with Foundry." },
  { id: "l-rust", title: "Rust / Anchor (Solana) pitfalls", category: "language", tags: ["rust", "solana", "anchor"], sev: "info",
    what: "missing signer/owner checks, raw AccountInfo (account substitution), init_if_needed reinit, unchecked numeric casts, panics (unwrap) as DoS, missing PDA seed/bump validation, arbitrary CPI.",
    find: "Check every account constraint; confirm overflow-checks; trace mint authority." },
  { id: "l-move", title: "Move (Sui / Aptos) pitfalls", category: "language", tags: ["move", "sui", "aptos"], sev: "info",
    what: "capability/signer not required on privileged entry, resource mishandling, hot-potato bypass, u64 truncation, generic type confusion.",
    find: "Confirm minting needs a capability only an attested path produces; check public(friend)/entry visibility." },
  { id: "l-cairo", title: "Cairo (Starknet) pitfalls", category: "language", tags: ["cairo", "starknet"], sev: "info",
    what: "missing get_caller_address role asserts, felt252 wraparound (use checked u256), reentrancy via external calls, unguarded replace_class_hash upgrades.",
    find: "Assert caller role on every privileged entrypoint; prefer u256 for money math." },
  { id: "l-go", title: "Go pitfalls", category: "language", tags: ["go", "cosmos"], sev: "info",
    what: "unchecked errors, nil deref, race conditions, SSRF in http clients, path traversal, weak randomness (math/rand), command injection via os/exec with interpolation.",
    find: "Check error handling on auth paths; -race for concurrency; exec.Command arg arrays not shell strings." },
  { id: "l-js", title: "JavaScript / Node pitfalls", category: "language", tags: ["javascript", "node", "typescript"], sev: "info",
    what: "prototype pollution, SSRF, command injection (child_process interpolation), unsafe eval/Function, regex DoS (ReDoS), insecure deserialization, dependency confusion, XSS via dangerouslySetInnerHTML.",
    find: "Trace user input to exec/eval/innerHTML; check __proto__ merges; audit deps." },
  { id: "l-python", title: "Python pitfalls", category: "language", tags: ["python"], sev: "info",
    what: "pickle deserialization RCE, SSTI (Jinja2), command injection (os.system/subprocess shell=True), YAML load, SSRF (requests), path traversal, assert used for auth (stripped with -O).",
    find: "Check for shell=True, yaml.load, pickle.loads on untrusted data." },
  { id: "l-java", title: "Java pitfalls", category: "language", tags: ["java"], sev: "info",
    what: "deserialization (ysoserial), XXE, SSRF, SpEL/OGNL injection, Log4Shell-style JNDI, path traversal, SQLi.",
    find: "Look for readObject on untrusted data, XML parsers without secure config, JNDI lookups." },
  { id: "l-c", title: "C / C++ pitfalls", category: "language", tags: ["c", "cpp", "memory"], sev: "info",
    what: "buffer overflows, use-after-free, integer overflows, format strings, off-by-one, uninitialized memory.",
    find: "Audit memory ops and bounds; fuzz (AFL++, libFuzzer); run ASan/UBSan." },
  { id: "l-php", title: "PHP pitfalls", category: "language", tags: ["php"], sev: "info",
    what: "LFI/RFI, type juggling (== vs ===), object injection (unserialize), SQLi, command injection, weak comparisons in auth.",
    find: "Check unserialize on input, loose comparisons in login, include of user paths." },

  // ---------------- METHODOLOGY ----------------
  { id: "me-workflow", title: "The bug-bounty workflow", category: "method", tags: ["process"], sev: "info",
    what: "Read scope/rules → map the surface → understand the tech → test the high-value classes → verify → dedup → report.",
    find: "Spend most time understanding the target and modeling intended behavior; bugs are deviations from intent.",
    note: "Shakuni mirrors this: Program Intake → Repository Analysis → GitHub Evidence → the tools → Report Builder." },
  { id: "me-scope", title: "Reading scope & rules", category: "method", tags: ["scope", "rules"], sev: "info",
    what: "In-scope assets, excluded classes, test restrictions (no DoS, own accounts, sandbox/testnet), eligibility (account naming), safe harbor.",
    find: "Make a checklist of what's in/out and what's explicitly excluded BEFORE testing; it tells you where the accepted bugs are.",
    note: "Excluded-class lists often reveal where the team expects (and has hardened) bugs." },
  { id: "me-triage", title: "Triage before you report", category: "method", tags: ["triage", "verify"], sev: "info",
    what: "In-scope asset? Attacker-controlled input? Crosses a security boundary? Real secret vs artifact? Already public? Reproducible PoC?",
    find: "Every lead must pass all six. A pattern match is not a bug.",
    note: "The Contract Scanner embeds this rubric; it's what keeps false positives out of reports." },
  { id: "me-dedup", title: "Prior-art / dedup", category: "method", tags: ["dedup"], sev: "info",
    what: "Check the repo's issues/PRs/commits, published audits, CVEs, and past disclosures before filing.",
    find: "A known bug, even a rejected PoC, is a duplicate and costs you.",
    note: "Shakuni Prior-Art Checker searches GitHub issues/PRs." },
  { id: "me-report", title: "Writing the report", category: "method", tags: ["report"], sev: "info",
    what: "Title, affected asset/version, clear reproduction steps, a working PoC, honest impact, and a dedup note.",
    find: "Make it independently reproducible; a triager who can't reproduce will close it.",
    note: "Shakuni Report Builder generates this; capture the PoC in the Foundry Harness." },
  { id: "me-cvss", title: "Severity (CVSS) basics", category: "method", tags: ["cvss", "severity"], sev: "info",
    what: "Severity is driven by impact (C/I/A) and exploitability (attack vector, complexity, privileges, user interaction).",
    find: "Argue realistic impact and a plausible attack scenario, not the theoretical maximum." },
  { id: "me-safeharbor", title: "Disclosure & safe harbor", category: "method", tags: ["disclosure", "legal"], sev: "info",
    what: "Only test what's authorized; follow the program's disclosure timeline; safe harbor protects good-faith, in-scope testing.",
    find: "Never exploit beyond proof, never touch others' data or funds, and keep findings confidential until consented." },

  // ---------------- TOOLS (external ↔ Shakuni) ----------------
  { id: "t-burp", title: "Burp Suite", category: "tool", tags: ["web", "proxy"], sev: "info",
    what: "Intercepting proxy, repeater, intruder, scanner, the standard web-app testing suite.",
    find: "Intercept, modify, replay, and fuzz HTTP.", note: "Shakuni in-house: Request Workbench (repeater + IDOR matrix)." },
  { id: "t-slither", title: "Slither", category: "tool", tags: ["web3", "static"], sev: "info",
    what: "Solidity static analyzer with many detectors.",
    find: "Run against contracts for known vuln patterns.", note: "Shakuni in-house: Solidity Analyzer (AST) + Contract Scanner (regex)." },
  { id: "t-foundry", title: "Foundry (forge / anvil / cast)", category: "tool", tags: ["web3", "testing"], sev: "info",
    what: "Solidity testing, fuzzing, invariant testing, forking, and chain interaction.",
    find: "Write tests/PoCs; fork testnets; call contracts.", note: "Shakuni in-house: Foundry PoC Harness + Chain Lab; raw forge in the Terminal." },
  { id: "t-nmap", title: "nmap", category: "tool", tags: ["network", "scan"], sev: "info",
    what: "Port/service scanning and scripted enumeration.",
    find: "Map hosts and services.", note: "External (run via the Terminal). No in-app equivalent, network scanning needs the binary." },
  { id: "t-ffuf", title: "ffuf / gobuster", category: "tool", tags: ["recon", "fuzzing"], sev: "info",
    what: "Fast content/parameter fuzzing.",
    find: "Discover hidden paths and params.", note: "External; pair with the Request Workbench to probe findings." },
  { id: "t-sqlmap", title: "sqlmap", category: "tool", tags: ["web", "sqli"], sev: "info",
    what: "Automated SQL injection detection and exploitation.",
    find: "Confirm and exploit SQLi.", note: "External (Python)." },
  { id: "t-nuclei", title: "nuclei", category: "tool", tags: ["scan", "templates"], sev: "info",
    what: "Template-based vulnerability scanning (CVEs, misconfig, takeovers).",
    find: "Mass-check known issues across hosts.", note: "External; good for breadth, verify every hit." },
  { id: "t-recon", title: "subfinder / amass / httpx / gau", category: "tool", tags: ["recon"], sev: "info",
    what: "Subdomain enumeration, live-host probing, and historical URL collection.",
    find: "Build the target map.", note: "External; feed results into Shakuni's analysis + Request Workbench." },
  { id: "t-frida", title: "Frida / objection", category: "tool", tags: ["mobile", "instrumentation"], sev: "info",
    what: "Dynamic instrumentation to hook and bypass (e.g., cert pinning) in mobile/desktop apps.",
    find: "Hook functions at runtime.", note: "External; needs a device/emulator." },
  { id: "t-ghidra", title: "Ghidra / IDA / radare2", category: "tool", tags: ["binary", "reversing"], sev: "info",
    what: "Disassemblers/decompilers for binary reverse engineering.",
    find: "Analyze and understand binaries.", note: "External; Ghidra is free." },
  { id: "t-jwt", title: "jwt_tool", category: "tool", tags: ["auth", "jwt"], sev: "info",
    what: "JWT analysis and attacks (alg none, confusion, cracking).",
    find: "Tamper and test tokens.", note: "External; Shakuni Chain Lab covers the ECDSA/keccak/EIP-712 side." },
  { id: "t-mitmproxy", title: "mitmproxy", category: "tool", tags: ["proxy", "mobile"], sev: "info",
    what: "Scriptable intercepting proxy, useful for mobile/API traffic.",
    find: "Intercept and script request/response flows.", note: "External; the Request Workbench covers craft-and-replay." },
];
