export type ChainModel = "account" | "utxo" | "hybrid" | "object" | "resource";
export type ResearchLayer =
  | "cryptography" | "consensus" | "execution" | "state" | "transactions"
  | "mempool" | "p2p" | "rpc" | "smart-contracts" | "cross-chain" | "wallets"
  | "custody" | "defi" | "oracles" | "governance" | "economics" | "infrastructure"
  | "privacy" | "data-availability" | "sequencing" | "bridges" | "identity";

export interface BlockchainResearchDomain {
  id: string; name: string; models: ChainModel[]; layers: ResearchLayer[];
  invariants: string[]; mutationFamilies: string[]; safeEnvironments: string[];
}

export const CRYPTO_RESEARCH_DOMAINS: BlockchainResearchDomain[] = [
  {id:"evm",name:"EVM / Account-Based Chains",models:["account"],layers:["execution","state","transactions","mempool","rpc","smart-contracts","cryptography"],invariants:["transaction nonce is valid","signature authenticates intended sender","gas accounting is conserved","state transition is deterministic","revert restores state","access control matches caller","chain/domain binding prevents replay"],mutationFamilies:["nonce","chain-id","calldata","gas","value","storage","replay","signature"],safeEnvironments:["local EVM","private devnet","authorized testnet"]},
  {id:"utxo",name:"Bitcoin / UTXO",models:["utxo"],layers:["cryptography","consensus","transactions","mempool","p2p","state","rpc"],invariants:["inputs reference valid UTXOs","inputs cannot be spent twice","input value covers outputs and fee","scripts satisfy spending conditions","block linkage and PoW rules hold","coinbase maturity and issuance hold","serialization and sighash rules hold"],mutationFamilies:["outpoint","script","sequence","locktime","sighash","fee","block-header","replay"],safeEnvironments:["regtest","private test network","authorized testnet"]},
  {id:"solana-svm",name:"Solana / SVM",models:["account"],layers:["execution","state","transactions","p2p","rpc","smart-contracts","cryptography"],invariants:["required signatures authenticate intended signers","transaction sanitization rejects malformed relationships","account ownership/writability rules hold","PDA derivation constraints hold","CPI signer/account semantics hold","lamport conservation holds","failed transactions do not commit intermediate state","upgrade authority matches expectations"],mutationFamilies:["account-order","signer","writable","instruction-data","PDA-seed","CPI","blockhash","compute-budget"],safeEnvironments:["local validator","devnet","authorized testnet"]},
  {id:"cosmos-cometbft",name:"Cosmos SDK / CometBFT",models:["account"],layers:["consensus","execution","state","transactions","mempool","p2p","rpc","cross-chain"],invariants:["validator voting power is correct","votes bind height and round","vote signatures authenticate validators","commit binds correct block","duplicate/conflicting votes are handled","state transitions are deterministic","IBC packet/channel commitments remain consistent"],mutationFamilies:["height","round","block-id","vote-type","validator-id","signature","packet-sequence","timeout"],safeEnvironments:["local multi-node network","private testnet","authorized testnet"]},
  {id:"move-resource",name:"Move / Resource-Oriented Chains",models:["resource"],layers:["smart-contracts","execution","state","transactions","cryptography"],invariants:["resources cannot be duplicated","resource abilities constrain movement","signer authority matches sender","package/module upgrade policy holds","state transitions are deterministic"],mutationFamilies:["resource-owner","signer","module","upgrade","type","transaction-order"],safeEnvironments:["local node","private testnet","authorized testnet"]},
  {id:"rollups",name:"Rollups / L2",models:["account","hybrid"],layers:["execution","state","sequencing","data-availability","bridges","rpc","cross-chain"],invariants:["L2 state follows canonical derivation","sequencer output obeys validity rules","batch/message ordering is preserved","withdrawal proofs bind to correct state","DA assumptions are explicit","L1/L2 replay is prevented"],mutationFamilies:["batch","sequence","deposit","withdrawal","message","proof","timestamp","fee"],safeEnvironments:["local rollup stack","private devnet","authorized testnet"]},
  {id:"bridges",name:"Bridges / Cross-Chain Messaging",models:["account","utxo","hybrid"],layers:["bridges","cross-chain","cryptography","consensus","state","oracles"],invariants:["message origin is authenticated","destination domain is bound","sequence cannot replay","mint/burn/lock/unlock accounting is conserved","threshold assumptions hold","finality assumptions are explicit","failed delivery cannot create unbacked value"],mutationFamilies:["source-chain","destination-chain","sequence","nonce","proof","attestation","relayer","finality"],safeEnvironments:["local fork","private bridge devnet","authorized testnet"]},
  {id:"stablecoins",name:"Stablecoins / Token Issuers",models:["account"],layers:["smart-contracts","cryptography","state","cross-chain","custody","governance"],invariants:["mint authority is authorized","burn accounting is conserved","supply matches accounting","pause/freeze controls are authorized","cross-chain supply stays backed","upgrade/admin controls follow policy"],mutationFamilies:["mint","burn","pause","freeze","role","upgrade","cross-chain-message"],safeEnvironments:["local fork","private devnet","authorized testnet"]},
  {id:"wallets-signers",name:"Wallets / Remote Signers / Custody",models:["account","utxo"],layers:["wallets","custody","cryptography","identity","rpc","infrastructure"],invariants:["unauthorized caller cannot cause signing","signed message binds domain/chain/context","identity cannot be confused","key selection is policy-compliant","attestation is validated","replay/stale requests are prevented","secrets do not cross logging boundaries"],mutationFamilies:["identity","message","domain","chain","nonce","attestation","key-id","authorization"],safeEnvironments:["mock signer","local enclave model","private devnet"]},
  {id:"defi",name:"DeFi / AMMs / Lending / Perps",models:["account"],layers:["defi","economics","smart-contracts","oracles","state"],invariants:["asset accounting is conserved","share accounting is conserved","collateral rules hold","oracle freshness/domain rules hold","liquidation preserves accounting","rounding cannot accumulate unexpected value","dependent operations remain atomic"],mutationFamilies:["price","oracle-time","rounding","liquidity","collateral","interest","liquidation","order"],safeEnvironments:["local fork","protocol testnet","simulation"]},
  {id:"oracles",name:"Oracle / Price / Attestation Systems",models:["account","hybrid"],layers:["oracles","cryptography","cross-chain","economics","identity"],invariants:["source identity is authenticated","freshness is enforced","timestamp/sequence constraints hold","domain binding prevents replay","quorum assumptions hold","stale/conflicting data cannot silently become trusted"],mutationFamilies:["price","timestamp","sequence","source-id","signature","quorum","replay"],safeEnvironments:["local oracle simulator","private devnet"]},
  {id:"governance",name:"Governance / DAO / Upgrade Control",models:["account"],layers:["governance","smart-contracts","economics","identity","state"],invariants:["proposal authorization is correct","voting power uses intended snapshot","quorum/threshold rules hold","execution binds approved proposal","timelocks cannot be bypassed","upgrade authority follows governance policy"],mutationFamilies:["snapshot","vote","delegation","quorum","timelock","proposal-id","upgrade"],safeEnvironments:["local fork","private governance devnet"]},
  {id:"p2p",name:"P2P / Gossip / Networking",models:["account","utxo","hybrid"],layers:["p2p","consensus","mempool","rpc","infrastructure"],invariants:["peer messages are validated","message types cannot cross boundaries unexpectedly","replay/duplicates are handled","peer metadata cannot corrupt consensus state","resource limits are enforced"],mutationFamilies:["message-type","sender","ordering","duplicate","replay","payload-size","connection-state"],safeEnvironments:["isolated local network","private multi-node testnet"]},
  {id:"mev-sequencing",name:"MEV / Sequencing / Ordering",models:["account"],layers:["sequencing","mempool","economics","execution"],invariants:["ordering rules match protocol","priority/fee accounting is correct","private-ordering promises hold","sequencer constraints cannot bypass authorization","cross-domain ordering assumptions are explicit"],mutationFamilies:["ordering","priority","fee","bundle","timestamp","sequence"],safeEnvironments:["local simulator","private devnet"]},
  {id:"privacy-zk",name:"Privacy / ZK / Proof Systems",models:["account","hybrid"],layers:["privacy","cryptography","execution","state","cross-chain"],invariants:["proof verifies intended statement","public inputs bind correct state/domain","nullifiers prevent double-use","commitments bind intended messages","setup/proving assumptions are explicit"],mutationFamilies:["public-input","proof","commitment","nullifier","domain","replay"],safeEnvironments:["local prover/verifier","testnet"]},
  {id:"data-availability",name:"Data Availability",models:["hybrid"],layers:["data-availability","consensus","cross-chain","state"],invariants:["availability commitments bind intended data","sampling cannot accept unavailable data","reconstruction assumptions are explicit","data roots correspond to canonical batch"],mutationFamilies:["data-root","chunk","proof","sample","availability-window"],safeEnvironments:["local DA simulator","private testnet"]},
  {id:"infrastructure",name:"Node / RPC / Indexer / Cloud Infrastructure",models:["account","utxo","hybrid"],layers:["rpc","infrastructure","identity","custody"],invariants:["privileged RPC requires authorization","node/signing endpoints are protected","indexers remain canonical","configuration preserves controls","secrets do not cross logging boundaries"],mutationFamilies:["rpc-method","auth","configuration","chain-id","endpoint","secret"],safeEnvironments:["local node","private cloud sandbox"]},
];

export const UNIVERSAL_BLOCKCHAIN_CHECKLIST = [
"chain identity / domain separation","transaction authenticity","replay resistance","nonce / sequence correctness",
"serialization / deserialization","signature verification","key authorization","state transition determinism",
"state rollback / atomicity","fee / gas conservation","asset supply conservation","ownership / authority",
"upgrade authority","timelock enforcement","oracle freshness","oracle authenticity","cross-chain authentication",
"cross-chain replay resistance","finality assumptions","validator identity","validator voting power",
"vote uniqueness","block binding","commit/certificate validity","equivocation handling","mempool consistency",
"transaction ordering","P2P validation","resource/account access control","cryptographic domain separation",
"attestation lifecycle","remote signer authorization","secret boundary integrity","event/log consistency",
"indexer canonicality","governance execution binding","economic invariant preservation"
] as const;
