import type { Manifest } from "./ingest.ts";
import { harnessForLead } from "./harness-registry.ts";
import type { HarnessPlanItem, RepoHypothesis } from "./report.ts";
import type { HarnessResult } from "./rust-harness.ts";

/**
 * Turns leads + imported PR data into a harness plan, and drafts a submission
 * when a harness actually breaks.
 *
 * "Generation" here is honest: for a lead with a registered harness template,
 * the flow generates (installs + parameterizes + compiles + runs) that real
 * harness. For a lead with no template yet, it says so, it does not fabricate
 * a harness or a result for code it has no template for.
 */

/** PRs from a lead's cross-refs that flag its area (used as the "why run this" trigger). */
function triggerPRs(h: RepoHypothesis): { label: string; url?: string }[] {
  return h.crossRefs.filter((c) => c.source === "github-pr").slice(0, 2).map((c) => ({ label: c.label, url: c.url }));
}

/** Build the plan: which leads get a generated harness, which are pending. Results filled in by `annotatePlan`. */
export function planHarnesses(hypotheses: RepoHypothesis[]): HarnessPlanItem[] {
  return hypotheses.map((h) => {
    const def = harnessForLead(h.id);
    if (def) {
      return {
        leadId: h.id, leadTitle: h.title, status: "generated-and-run", property: def.property, crate: def.crate,
        triggerPRs: triggerPRs(h),
        note: `A real harness exists for this lead; the flow installs it into ${def.crate}, compiles it, and runs it against the cloned code.`,
      };
    }
    return {
      leadId: h.id, leadTitle: h.title, status: "pending-no-template", triggerPRs: triggerPRs(h),
      note: "No harness template yet. Adding one (a Rust property test for this component) is the next engineering step; the product will not fabricate a result without it.",
    };
  });
}

/** Fill each plan item's `result` from the executed harness results. */
export function annotatePlan(plan: HarnessPlanItem[], executed: HarnessResult[]): HarnessPlanItem[] {
  return plan.map((p) => {
    const run = executed.find((e) => e.property === p.property);
    return run ? { ...p, result: run.result } : p;
  });
}

/** Draft a submission from a BROKEN harness. Only ever called when a real break was reproduced. */
export function draftSubmission(broken: HarnessResult, repo: string, maxSeverity: string | null, manifest?: Manifest): string {
  const commit = manifest?.commit ?? broken.commit;
  return [
    `### Title`,
    `${broken.property} violated in ${broken.crate} (${repo})`,
    ``,
    `### Summary`,
    `A property harness driving the real \`${broken.crate}\` found a case that violates the safety property \`${broken.property}\`. The violation was observed on the code at commit \`${commit}\`.`,
    ``,
    `### Affected component`,
    `${broken.crate}, ${repo} @ ${commit}`,
    ``,
    `### Steps to reproduce`,
    `1. Clone ${repo} at commit ${commit}.`,
    `2. Install the Shakuni harness for this property and run it deterministically:`,
    `   \`SHAKUNI_SEED=<seed-from-counterexample> cargo test -p ${broken.crate} --test <harness> -- --nocapture\``,
    `3. Observe the counterexample below reproduce.`,
    ``,
    `### Counterexample`,
    broken.counterexample ?? "(none captured)",
    ``,
    `### Impact`,
    `This is a consensus-safety property. Confirm the concrete impact (e.g. two conflicting commits / forged quorum) before claiming a severity. Program max severity for this target: ${maxSeverity ?? "unspecified"}.`,
    ``,
    `### Reviewer checklist before submission`,
    `- [ ] Reproduced independently from a clean clone.`,
    `- [ ] Minimized the counterexample.`,
    `- [ ] Confirmed it is not a harness artifact (the property and its assumptions are correct).`,
    `- [ ] Demonstrated real security impact.`,
    `- [ ] Checked scope and duplicates.`,
    ``,
    `> Draft generated by Shakuni. DO NOT submit until every box above is checked by a human.`,
  ].join("\n");
}
